### ISSUE TITLE
Allow typed tokens of the Tavor format to be externally defined

### ISSUE THREAD

**Issue by zimmski** [zimmski/tavor#39]
Right now every typed token has to be coded into the format parser. This makes extending the platform's main format unpractical. The registration of typed tokens and their arguments should be possible without the consensus of the parser code.

**Comment by yblein** [comment]
Externalizing typed token definitions would require to expose some of the internals of the parser: the `Existing` attribute of the `Sequence` type tries to parse a "not in" expression before returning. If `Existing` is to be described outside of the parser, it still has to be able to call `parseExpressionOperatorNotIn` one way or another.
Are you ok with exposing such methods?

**Comment by zimmski** [comment]
(I just noticed that this issue was created when the "typed tokens" still where called "special tokens". I changed the issue description.)

This issue concerns only the `tavorParser.parseTypedTokenDefinition` method especially this part https://github.com/zimmski/tavor/blob/master/parser/tavor.go#L1571-L1648

It is true that `Existing` does parse a "not in" but removing the code for `Existing` from the parser should be done with issue #38. However, exposing some interface methods of the parser will be indefinitely necessary.

**Comment by yblein** [comment]
Maybe the registration of typed tokens should stay in `parser` package so that the parser remains the only place dependent on the tavor format? Then the solution would be to perform the registration in another file (like parser/typed.go) with some helper functions allowing to register a typed token easily.

**Comment by zimmski** [comment]
That would be an isolated solution (which I usually prefer!) but in this case I do not think that it should be parser specific. Typed tokens are just a feature a format can have in some way. If they are not supported it just means that the format cannot be extend with more types than the format supports e.g. regular expressions are limited to their predefined character classes.
So I think that the registration can be safely done in the `token` package (e.g. /token/typed.go) in the same way it is accomplished with the filters https://github.com/zimmski/tavor/blob/master/fuzz/filter/filter.go + the argument handling of the tokens. And the registration of each token+arguments can be done in the specific token file.
Does this sound plausible to you?

**Comment by yblein** [comment]
Indeed, registering tokens in the `token` package surely makes sense. I'll look into that direction.

The proposal is written down and being proofread! I feel I'm being too vague on what should be done in order to support the definition of an instruction set, but I can't see yet what is missing exactly for this specific use case...

**Comment by zimmski** [comment]
If you like, you can write me a mail with your observations. We can discuss it and maybe you get some more insides. It is important to me that you write an awesome proposal since it increases the probability that you are accepted and that we get a slot for the project. There are more variables in the mix than just my opinion.
