### ISSUE TITLE
"stringer" is missing in the build dependencies

### ISSUE THREAD

**Issue by Skomski** [zimmski/tavor#79]
go clean -i ./...
go clean -i -race ./...
go install -v ./...
github.com/zimmski/tavor
github.com/zimmski/tavor/log
github.com/zimmski/tavor/rand
github.com/zimmski/tavor/examples/complete/implementation
github.com/zimmski/tavor/test/assert
github.com/zimmski/tavor/examples/complete
github.com/zimmski/tavor/test
github.com/zimmski/tavor/token
github.com/zimmski/tavor/token/primitives
github.com/zimmski/tavor/token/constraints
github.com/zimmski/tavor/token/aggregates
github.com/zimmski/tavor/reduce/strategy
github.com/zimmski/tavor/token/filters
github.com/zimmski/tavor/token/lists
github.com/zimmski/tavor/token/variables
github.com/zimmski/tavor/fuzz/filter
github.com/zimmski/tavor/token/sequences
github.com/zimmski/tavor/graph
github.com/zimmski/tavor/token/conditions
github.com/zimmski/tavor/token/expressions
github.com/zimmski/tavor/fuzz/strategy
github.com/zimmski/tavor/parser
github.com/zimmski/tavor/cmd/tavor
go generate ./...
reduce/strategy/strategy.go:31: running "stringer": exec: "stringer": executable file not found in $PATH
Makefile:23: recipe for target 'install' failed
make: *** [install] Error 1
[1]    6810 exit 2     make install

**Comment by zimmski** [comment]
You have to run `go get -u golang.org/x/tools/cmd/stringer` or just `make`. `stringer` is used to generate some code of Tavor. I will remove it from the default install target since most people won't touch that part of Tavor.

**Comment by zimmski** [comment]
The latest revision 962b500067bc58750e052e6210453b7a5931c4a9 does not depend on "go generate" anymore. You can fetch it with:
```bash
go get -u github.com/zimmski/tavor
cd $GOPATH/src/github.com/zimmski/tavor
make dependencies
make install
```
